add_newline = true  
  
format = "$username$hostname$directory$time$character"  
  
[username]  
show_always = true  
style_user = "bold fg:#ffffff bg:#32374d"    
format = "[ $user ]($style)[](fg:#32374d bg:#3f475f)"  
  
[hostname]  
ssh_only = false   
style = "bold fg:#ffffff bg:#3f475f"   
format = "[@$hostname ]($style)[](fg:#3f475f bg:#3fc4de)"  
  
[directory]  
style = "bold fg:#ffffff bg:#3fc4de"   
format = "[ $path ]($style)[](fg:#3fc4de bg:#1e88e5)"  
  
[time]  
disabled = false  
time_format = "%H:%M"  
style = "bold fg:#ffffff bg:#1e88e5"   
format = "[ $time ]($style)[](fg:#1e88e5 bg:#1e88e5)"  
  
[character]  
success_symbol = "[](bold fg:#1e88e5 bg:none)"  
error_symbol   = "[](bold fg:#FF0000 bg:none)"   
